.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. odan_qt test_odan_qt
clean: FORCE
	$(MAKE) -C .. odan_qt_clean test_odan_qt_clean
check: FORCE
	$(MAKE) -C .. test_odan_qt_check
odan-qt odan-qt.exe: FORCE
	 $(MAKE) -C .. odan_qt
apk: FORCE
	$(MAKE) -C .. odan_qt_apk
